---
title: "People"
---

-   **Founders and co-chairs**: Ye Ting (University of Washington) and Jingyi Liu (Eli Lily)

-   **Advisor**: Frank Bretz (Novartis), Dan Rubin (FDA), and Andreas Brandt (BfArM)

-   **Subteam co-leaders:**

    -   **Education sub-team:** Kelly Van Lancker (Ghent) and Dominic Magirr (Novartis)

    -   **Software sub-team**: Dong Xi (Gilead), Yanyao Yi (Eli Lilly), Liming Li (AstraZeneca)

    -   **Standardization and outreach sub-team**: Yu Du (Eli Lilly) and Daniel Backenroth (Johnson & Johnson)

    -   **Advancement sub-team:** Bingkai Wang (University of Michigan)

-   **Secretary**: Hongfei Li (Revolution Medicines)

**Members**

| First Name | Last Name    | Affiliation                                 |
|------------|--------------|---------------------------------------------|
| Alan       | Wu           | BeOne Medicines                             |
| Alex       | Ocampo       | Roche                                       |
| Alex       | Sverdlov     | Novartis                                    |
| Alexander  | Przybylski   | Novartis                                    |
| Andreas    | Brandt       | BfArM                                       |
| Arjun      | Sondhi       | Feinstein Institutes for Medical Research   |
| Bingkai    | Wang         | University of Michigan, Biostatistics       |
| Bingying   | Xie          | AstraZeneca                                 |
| Craig      | Wang         | Novartis                                    |
| Daniel     | Backenroth   | Johnson & Johnson                           |
| Daniel     | Rubin        | FDA                                         |
| Daniel     | Sabanés Bové | RCONIS                                      |
| Darren     | Scott        | Astrazeneca                                 |
| Devan      | Mehrotra     | Merck                                       |
| Dominic    | Magirr       | Novartis                                    |
| Dong       | Xi           | Gilead                                      |
| Frank      | Bretz        | Novartis                                    |
| Gregory    | Chen         | Merck                                       |
| Hongfei    | Li           | Revolution Medicines                        |
| Jiajun     | Xu           | Johnson & Johnson                           |
| Jiawei     | Wei          | Novartis                                    |
| Jingyi     | Liu          | Eli Lilly                                   |
| Jonathan   | Chipman      | University of Utah                          |
| Jozefien   | Buyze        | Johnson & Johnson                           |
| Jun        | Shao         | University of Wisconsin-Madison, Statistics |
| Kayla      | Irish        | University of Washington, Statistics        |
| Kelly Van  | Lancker      | Ghent University, Applied Math/CS/Stat      |
| Ken        | Wu           | BeOne Medicines                             |
| Leiya      | Han          | PPD                                         |
| Liming     | Li           | Astrazeneca                                 |
| Mark       | Baillie      | Novartis                                    |
| Marlena    | Bannick      | University of Washington, Biostatistics     |
| Mike       | Friesenhahn  | Roche/GNE                                   |
| Oleksandr  | Savenkov     | Bristol Myers Squibb                        |
| Olga       | Kuznetsova   | Merck                                       |
| Ray        | Lin          | Genentech                                   |
| Sarwar     | Mozumder     | GSK                                         |
| Satrajit   | Roychoudhury | Pfizer                                      |
| Ting       | Ye           | University of Washington, Biostatistics     |
| Victoria   | Johnson      | GSK                                         |
| Xin        | Zhang        | Pfizer                                      |
| Yanyao     | Yi           | Eli Lilly                                   |
| Yu         | Du           | Eli Lilly                                   |
