
---
title: "Clarifying the role of the Mantel–Haenszel risk difference estimator in randomized clinical trials"
description: "February 2026 Seminar by Yuhan Qian"
author: ""
date: "02/13/2026"
draft: false
categories:
  - journal club
---

**Topic:** Clarifying the role of the Mantel–Haenszel risk difference estimator in randomized clinical trials

**Datetime: Feb 13th Friday, 11am-12pm ET.**

**Presenter:** Dr. Yuhan Qian is a PhD student in the Department of Biostatistics, School of Public Health, University of Washington.

**Summary:** The Mantel–Haenszel (MH) risk difference estimator, commonly used in randomized clinical trials for binary outcomes, calculates a weighted average of stratum-specific risk difference estimators. Traditionally, this method requires the stringent assumption that risk differences are homogeneous across strata, also known as the common (constant) risk difference assumption. In our paper, we relax this assumption and adopt a modern perspective, viewing the MH risk difference estimator as an approach for covariate adjustment in randomized clinical trials, distinguishing its use from that in meta-analysis and observational studies. We demonstrate that, under reasonable restrictions on risk difference variability, the MH risk difference estimator consistently estimates the average treatment effect within a standard super-population framework, which is often the primary interest in randomized clinical trials, in addition to estimating a weighted average of stratum-specific risk differences. We rigorously study its properties under the large-stratum and sparse-stratum asymptotic regimes, as well as under mixed-regime settings. Furthermore, for either estimand, we propose a unified robust variance estimator that improves over the popular variance estimators by Greenland and Robins and Sato et al. and has provable consistency across these asymptotic regimes, regardless of assuming common risk differences. Extensions of our theoretical results also provide new insights into the MH test, the post-stratification estimator, and settings with multiple treatments. Our findings are thoroughly validated through simulations and a clinical trial example.

**Recording:** 
```{=html}
<iframe src="https://drive.google.com/file/d/16E8j1gYuW4_HFHE-6AzZ1upICpEgfiNd/preview" width="640" height="480" allowfullscreen="true" allow="autoplay"></iframe>
```

```{=html}
<script src="https://giscus.app/client.js"
        data-repo="carswg/carswg.github.io"
        data-repo-id="R_kgDOLX8xOg"
        data-category="General"
        data-category-id="DIC_kwDOLX8xOs4CeZQB"
        data-mapping="title"
        data-strict="1"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="light_high_contrast"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>
```
