---
title: "Improve the Precision of Area Under the Curve Estimation for Recurrent Events Through Covariate Adjustment"
description: "October 2025 Seminar by Jiren Sun"
author: ""
date: "10/10/2025"
draft: false
categories:
  - journal club
---

**Topic:** Improve the Precision of Area Under the Curve Estimation for Recurrent Events Through Covariate Adjustment

**Datetime: Oct 10th Friday, 11am-12pm ET.**

**Presenter:** Jiren Sun from Eli Lilly

**Summary:** The area under the curve (AUC) of the mean cumulative function (MCF) has recently been introduced as a novel estimand for evaluating treatment effects in recurrent event settings, offering an alternative to the commonly used Lin-Wei-Yang-Ying (LWYY) model. The AUC of the MCF provides a clinically interpretable summary measure that captures the overall burden of disease progression, regardless of whether the proportionality assumption holds. To improve the precision of the AUC estimation while preserving its unconditional interpretability, we propose a nonparametric covariate adjustment approach. This approach guarantees efficiency gain compared to unadjusted analysis, as demonstrated by theoretical asymptotic distributions, and is universally applicable to various randomization schemes, including both simple and covariate-adaptive designs. Extensive simulations across different scenarios further support its advantage in increasing statistical power. Our findings highlight the importance of covariate adjustment for the analysis of AUC in recurrent event settings, offering practical guidance for its application in randomized clinical trials.

**Recording:** 
```{=html}
<iframe src="https://drive.google.com/file/d/1ru6FKSZQWyeYy33uwhPlGL7nzykqnooG/preview" width="640" height="480" allowfullscreen="true" allow="autoplay"></iframe>
```

```{=html}
<script src="https://giscus.app/client.js"
        data-repo="carswg/carswg.github.io"
        data-repo-id="R_kgDOLX8xOg"
        data-category="General"
        data-category-id="DIC_kwDOLX8xOs4CeZQB"
        data-mapping="title"
        data-strict="1"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="light_high_contrast"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>
```
