
---
title: "Practical considerations when using covariate-adjusted log-rank test, including adaptive designs"
description: "April 2026 Seminar by Daniel Backenroth"
author: ""
date: "04/10/2026"
draft: false
categories:
  - journal club
---

**Topic:** Practical considerations when using covariate-adjusted log-rank test, including adaptive designs

**Datetime: April 10th Friday, 11am-12pm ET.**

**Presenter:** Dr. Daniel Backenroth is a Fellow of Biostatistics at Johnson & Johnson.

**Summary:** This talk will describe how the covariate-adjusted log-rank test can be used to enhance the power of late-phase oncology studies with primary time-to-event endpoints. Using as a case study a metastatic colorectal cancer trial with overall survival as the primary endpoint, we demonstrate how to use historical data to estimate variance reductions achievable through different covariate adjustment strategies, including adjustment for a prognostic score. We also compare these strategies with respect to Type I error rate control, and show via a simulation study that inflation arising from embedding covariate adjustment in a group sequential design can be avoided. 

We also investigate adaptive designs that can be used to take advantage of increases in efficiency from the use of the covariate-adjusted log-rank test in trials with time-to-event endpoints. These adaptive designs are intended to address a key practical challenge in taking advantage of efficiency gains from this test, which is that the actual efficiency gain attained in a trial may differ from estimates of the efficiency gain at the design stage, and even from interim estimates during the trial. 


**Recording:** 
```{=html}
<iframe src="https://drive.google.com/file/d/17TFsFj399ESgz3_EX_JxrbJ5GfiwC_ig/preview" width="640" height="480" allowfullscreen="true" allow="autoplay"></iframe>
```

```{=html}
<script src="https://giscus.app/client.js"
        data-repo="carswg/carswg.github.io"
        data-repo-id="R_kgDOLX8xOg"
        data-category="General"
        data-category-id="DIC_kwDOLX8xOs4CeZQB"
        data-mapping="title"
        data-strict="1"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="light_high_contrast"
        data-lang="en"
        crossorigin="anonymous"
        async>
</script>
```
